
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        User
* GENERATION DATE:  02.02.2012
* CLASS FILE:       D:\xampplite\htdocs\zak\apps\contoh\model\classEntity/generated_classes/class.User.php
* FOR MYSQL TABLE:  tbl_user
* FOR MYSQL DB:     onewscom_zak
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("../resources/class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class User
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $usr_id;   // KEY ATTR. WITH AUTOINCREMENT

var $usr_fname;   // (normal Attribute)
var $usr_name;   // (normal Attribute)
var $usr_password;   // (normal Attribute)
var $usr_login;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function User()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getusr_id()
{
return $this->usr_id;
}

function getusr_fname()
{
return $this->usr_fname;
}

function getusr_name()
{
return $this->usr_name;
}

function getusr_password()
{
return $this->usr_password;
}

function getusr_login()
{
return $this->usr_login;
}

// **********************
// SETTER METHODS
// **********************


function setusr_id($val)
{
$this->usr_id =  $val;
}

function setusr_fname($val)
{
$this->usr_fname =  $val;
}

function setusr_name($val)
{
$this->usr_name =  $val;
}

function setusr_password($val)
{
$this->usr_password =  $val;
}

function setusr_login($val)
{
$this->usr_login =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM tbl_user WHERE usr_id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysqli_fetch_object($result);

$this->usr_id = $row->usr_id;
$this->usr_fname = $row->usr_fname;
$this->usr_name = $row->usr_name;
$this->usr_password = $row->usr_password;
$this->usr_login = $row->usr_login;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM tbl_user WHERE usr_id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->usr_id = ""; // clear key for autoincrement

$sql = "INSERT INTO tbl_user ( usr_fname,usr_name,usr_password,usr_login ) VALUES ( '$this->usr_fname','$this->usr_name','$this->usr_password','$this->usr_login' )";
$result = $this->database->query($sql);
$this->usr_id = mysqli_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE tbl_user SET  usr_fname = '$this->usr_fname',usr_name = '$this->usr_name',usr_password = '$this->usr_password',usr_login = '$this->usr_login' WHERE usr_id = $id ";

$result = $this->database->query($sql);



}



} // class : end

?>
<!-- end of generated class -->
